spring:
  application:
    name: PromptCraft
    description: AI-powered app builder application inspired by Lovable.dev
  datasource:
    url: jdbc:postgresql://localhost:5434/promptcraft
    username: promptcraft
    password: promptcraft123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect